In [1]:
import numpy as np

In [2]:
h=[30,20,5,8,9]

In [3]:
h

[30, 20, 5, 8, 9]

In [5]:
np.random.randint(18,21,500)

array([18, 20, 18, 18, 18, 19, 20, 20, 19, 20, 18, 18, 20, 18, 20, 20, 18,
       20, 20, 18, 18, 19, 19, 19, 19, 18, 18, 20, 20, 20, 20, 18, 18, 18,
       18, 18, 18, 19, 19, 20, 20, 19, 18, 20, 18, 20, 20, 20, 19, 19, 19,
       18, 20, 19, 19, 20, 20, 18, 19, 20, 19, 20, 18, 19, 19, 19, 18, 19,
       19, 20, 19, 19, 18, 20, 19, 18, 19, 19, 19, 18, 20, 18, 18, 19, 18,
       19, 18, 18, 19, 20, 19, 18, 18, 18, 19, 18, 20, 19, 18, 20, 18, 20,
       19, 20, 19, 19, 20, 19, 20, 20, 20, 20, 19, 18, 18, 18, 20, 19, 20,
       18, 19, 19, 19, 18, 18, 20, 20, 19, 20, 19, 19, 18, 19, 20, 18, 19,
       19, 19, 19, 20, 18, 19, 20, 19, 20, 18, 20, 18, 18, 18, 19, 20, 20,
       19, 18, 18, 18, 18, 20, 20, 19, 18, 18, 19, 18, 20, 19, 18, 18, 20,
       19, 19, 18, 19, 18, 20, 18, 19, 19, 18, 18, 20, 19, 20, 20, 20, 20,
       19, 19, 18, 19, 20, 18, 20, 19, 20, 18, 20, 18, 19, 20, 18, 19, 19,
       19, 19, 19, 18, 20, 18, 20, 20, 18, 20, 19, 18, 19, 20, 18, 19, 19,
       20, 19, 20, 20, 20

In [6]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [7]:
tuple(x**2 for x in s)

(36, 4, 9, 81, 49, 25, 64)

In [8]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
s

(36, 4, 9, 81, 49, 25, 64)

In [9]:
m=[]
for i in s:
    if i>30:
        m.append(i)

In [10]:
arr=np.array([20,50,30,70,80,40,36,54,23,9])

In [11]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23,  9])

In [12]:
arr+5

array([25, 55, 35, 75, 85, 45, 41, 59, 28, 14])

In [13]:
arr**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296, 2916,  529,   81])

In [14]:
arr[arr>50]



array([70, 80, 54])